
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class Add_Student extends javax.swing.JFrame {

    /**
     * Creates new form Add_Student
     */
    public Add_Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StudentPw = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        RollNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        StudentName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dobName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        StudentDept_Dropdown = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Section = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Semester = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EmailAd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Submit_btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-small.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 50, 233, 99);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 83));
        jLabel4.setText("Add Student");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 170, 250, 30);

        StudentPw.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StudentPw.setForeground(new java.awt.Color(22, 0, 83));
        StudentPw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        StudentPw.setOpaque(false);
        jPanel1.add(StudentPw);
        StudentPw.setBounds(820, 270, 250, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(115, 115, 115));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(820, 230, 180, 30);

        RollNo.setBackground(new java.awt.Color(255, 255, 255));
        RollNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RollNo.setForeground(new java.awt.Color(22, 0, 83));
        RollNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        RollNo.setOpaque(false);
        jPanel1.add(RollNo);
        RollNo.setBounds(470, 270, 250, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(115, 115, 115));
        jLabel7.setText("Roll No. :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 230, 180, 30);

        StudentName.setBackground(new java.awt.Color(255, 255, 255));
        StudentName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StudentName.setForeground(new java.awt.Color(22, 0, 83));
        StudentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        StudentName.setOpaque(false);
        jPanel1.add(StudentName);
        StudentName.setBounds(130, 270, 260, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 115, 115));
        jLabel5.setText("Student Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 230, 180, 30);

        dobName.setBackground(new java.awt.Color(255, 255, 255));
        dobName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dobName.setForeground(new java.awt.Color(22, 0, 83));
        dobName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        dobName.setOpaque(false);
        jPanel1.add(dobName);
        dobName.setBounds(130, 370, 260, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(115, 115, 115));
        jLabel8.setText("D.O.B. Name:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 330, 180, 30);

        StudentDept_Dropdown.setBackground(new java.awt.Color(255, 255, 255));
        StudentDept_Dropdown.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        StudentDept_Dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIT", "LIB", "ECE", "CCE" }));
        StudentDept_Dropdown.setOpaque(false);
        jPanel1.add(StudentDept_Dropdown);
        StudentDept_Dropdown.setBounds(470, 370, 260, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(115, 115, 115));
        jLabel9.setText("Department:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 330, 180, 30);

        Section.setBackground(new java.awt.Color(255, 255, 255));
        Section.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Section.setForeground(new java.awt.Color(22, 0, 83));
        Section.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Section.setOpaque(false);
        jPanel1.add(Section);
        Section.setBounds(820, 370, 250, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(115, 115, 115));
        jLabel10.setText("Section:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(820, 330, 180, 30);

        Semester.setBackground(new java.awt.Color(255, 255, 255));
        Semester.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Semester.setForeground(new java.awt.Color(22, 0, 83));
        Semester.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Semester.setOpaque(false);
        jPanel1.add(Semester);
        Semester.setBounds(130, 480, 260, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(115, 115, 115));
        jLabel11.setText("Semester:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 440, 180, 30);

        EmailAd.setBackground(new java.awt.Color(255, 255, 255));
        EmailAd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EmailAd.setForeground(new java.awt.Color(22, 0, 83));
        EmailAd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        EmailAd.setOpaque(false);
        jPanel1.add(EmailAd);
        EmailAd.setBounds(470, 480, 260, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(115, 115, 115));
        jLabel12.setText("Email Address:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(470, 440, 180, 30);

        Submit_btn.setBackground(new java.awt.Color(255, 255, 255));
        Submit_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(22, 0, 83));
        Submit_btn.setText("Submit");
        Submit_btn.setBorder(null);
        Submit_btn.setBorderPainted(false);
        Submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Submit_btn.setFocusPainted(false);
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Submit_btn);
        Submit_btn.setBounds(130, 570, 100, 38);

        Back_Btn.setBackground(new java.awt.Color(38, 36, 36));
        Back_Btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Go back");
        Back_Btn.setBorder(null);
        Back_Btn.setBorderPainted(false);
        Back_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back_Btn.setFocusPainted(false);
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(1070, 620, 90, 30);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1210, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
        try {
		File f1 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/StudentList.txt" );
		FileWriter fw = new FileWriter( f1, true );
                
		String stuname = StudentName.getText();
		String sturno = RollNo.getText();
		String stupass = StudentPw.getText();
		String studob = dobName.getText();
		String studept = (String)StudentDept_Dropdown.getSelectedItem();
		String stusec = Section.getText();
		String stusem = Semester.getText();
		String stumail = EmailAd.getText();
                
		String total = stuname + "," + sturno + "," + stupass + "," + studob + "," + studept + "," + stusec + "," + stusem + "," + stumail + "\n";
		fw.write( total );
		fw.close();
	}
	
        catch( Exception f ) {
		JOptionPane.showMessageDialog( null, f );
	}
	
        JOptionPane.showMessageDialog( null, "Student Added!" );
        
	Add_Student ad = new Add_Student();
	ad.setVisible( true );
	dispose();        
    }//GEN-LAST:event_Submit_btnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Driver d = new Driver();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JTextField EmailAd;
    private javax.swing.JTextField RollNo;
    private javax.swing.JTextField Section;
    private javax.swing.JTextField Semester;
    private javax.swing.JComboBox<String> StudentDept_Dropdown;
    private javax.swing.JTextField StudentName;
    private javax.swing.JPasswordField StudentPw;
    private javax.swing.JButton Submit_btn;
    private javax.swing.JLabel background_image;
    private javax.swing.JTextField dobName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
