
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Erice
 */
public class Add_Subject extends javax.swing.JFrame {

    /**
     * Creates new form AddSubject
     */
    public Add_Subject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Submit_btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        sub1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sub2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        sub3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        sub6 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        sub5 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        sub4 = new javax.swing.JComboBox<>();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 697));

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 83));
        jLabel4.setText("Add Subject");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 170, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-small.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 50, 233, 99);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 115, 115));
        jLabel5.setText("Subject 1");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 230, 180, 30);

        Submit_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(22, 0, 83));
        Submit_btn.setText("Submit");
        Submit_btn.setBorder(null);
        Submit_btn.setBorderPainted(false);
        Submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Submit_btn.setFocusPainted(false);
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Submit_btn);
        Submit_btn.setBounds(130, 570, 100, 38);

        Back_Btn.setBackground(new java.awt.Color(38, 36, 36));
        Back_Btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Go back");
        Back_Btn.setBorder(null);
        Back_Btn.setBorderPainted(false);
        Back_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back_Btn.setFocusPainted(false);
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(1070, 620, 90, 30);

        sub1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DCIT 24", "MATH 1", "COSC 60", "FITT 3", "INSY 50", "DCIT 50" }));
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });
        jPanel1.add(sub1);
        sub1.setBounds(130, 270, 260, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(115, 115, 115));
        jLabel6.setText("Subject 2");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 230, 180, 30);

        sub2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DCIT 24", "MATH 1", "COSC 60", "FITT 3", "INSY 50", "DCIT 50" }));
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });
        jPanel1.add(sub2);
        sub2.setBounds(460, 270, 260, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(115, 115, 115));
        jLabel9.setText("Department");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 440, 180, 30);

        department.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DIT", "LIB", "ECE", "CCE" }));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel1.add(department);
        department.setBounds(130, 480, 260, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(115, 115, 115));
        jLabel13.setText("Subject 3");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(810, 230, 180, 30);

        sub3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sub3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DCIT 24", "MATH 1", "COSC 60", "FITT 3", "INSY 50", "DCIT 50" }));
        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });
        jPanel1.add(sub3);
        sub3.setBounds(810, 270, 260, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(115, 115, 115));
        jLabel14.setText("Subject 6");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(810, 340, 180, 30);

        sub6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sub6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DCIT 24", "MATH 1", "COSC 60", "FITT 3", "INSY 50", "DCIT 50" }));
        sub6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub6ActionPerformed(evt);
            }
        });
        jPanel1.add(sub6);
        sub6.setBounds(810, 380, 260, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(115, 115, 115));
        jLabel15.setText("Subject 5");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 340, 180, 30);

        sub5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sub5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DCIT 24", "MATH 1", "COSC 60", "FITT 3", "INSY 50", "DCIT 50" }));
        sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub5ActionPerformed(evt);
            }
        });
        jPanel1.add(sub5);
        sub5.setBounds(460, 380, 260, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(115, 115, 115));
        jLabel10.setText("Subject 4");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 340, 180, 30);

        sub4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sub4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "DCIT 24", "MATH 1", "COSC 60", "FITT 3", "INSY 50", "DCIT 50" }));
        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });
        jPanel1.add(sub4);
        sub4.setBounds(130, 380, 260, 30);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1210, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
        try {
            File f1=new File("C:\\Users\\Erice\\OneDrive\\Documents\\NetBeansProjects\\AMS\\Records\\SubjectList.txt");
            FileWriter fw=new FileWriter(f1,true);
            String subdept=(String)department.getSelectedItem();
            String s1=(String)sub1.getSelectedItem();
            String s2=(String)sub2.getSelectedItem();
            String s3=(String)sub3.getSelectedItem();
            String s4=(String)sub4.getSelectedItem();
            String s5=(String)sub5.getSelectedItem();
            String s6=(String)sub6.getSelectedItem();
            String total=subdept+","+s1+","+s2+","+s3+","+s4+","+s5+","+s6+"\n";
            fw.write(total);
            fw.close();
        }
        catch(Exception f) {
            JOptionPane.showMessageDialog(null,f);
        }
        JOptionPane.showMessageDialog(null,"Subjects Added !");
        Add_Subject ad=new Add_Subject();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_Submit_btnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Driver d = new Driver();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1ActionPerformed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2ActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3ActionPerformed

    private void sub6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub6ActionPerformed

    private void sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub5ActionPerformed

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton Submit_btn;
    private javax.swing.JLabel background_image;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> sub1;
    private javax.swing.JComboBox<String> sub2;
    private javax.swing.JComboBox<String> sub3;
    private javax.swing.JComboBox<String> sub4;
    private javax.swing.JComboBox<String> sub5;
    private javax.swing.JComboBox<String> sub6;
    // End of variables declaration//GEN-END:variables
}
