
import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class Attendance_Roll extends javax.swing.JFrame {
    String[] stuname;
    String[] sturno;
    String[] studate;
    int rcnt = 0;

    /**
     * Creates new form Attendance_Roll
     */
    public Attendance_Roll() {
        initComponents();
        
        JPanel p0=new JPanel();
		p0.setLayout(null);
                
        try {
		File f1 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/UploadAttendance.txt" );
		Scanner rd = new Scanner( f1 );
		rd.useDelimiter( "\\n|," );
		
                while( rd.hasNextLine() ) {
			rcnt++;
			rd.nextLine();
		}
		
                rd.close();
		
                stuname = new String[ rcnt ];
		sturno = new String[ rcnt ];
		studate = new String[ rcnt ];
			
		Scanner sc = new Scanner( f1 );
		sc.useDelimiter( "\\n|," );
		
                for( int i=0;i<rcnt;i++ ) {
			sturno[i] = sc.next();
			stuname[i] = sc.next();
			studate[i] = sc.next();
		}
		
                sc.close();
	}
	
        catch( Exception f ) {
		JOptionPane.showMessageDialog( null, f );
	}
        
                     
        for( int i = 0; i < rcnt; i++ ) {                    
                
                String data[] = { sturno[i], stuname[i] };
                
                DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
                tblModel.addRow( data );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UploadAttendance_SubmitBtn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-small.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 50, 233, 99);

        UploadAttendance_SubmitBtn.setBackground(new java.awt.Color(255, 255, 255));
        UploadAttendance_SubmitBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UploadAttendance_SubmitBtn.setForeground(new java.awt.Color(22, 0, 83));
        UploadAttendance_SubmitBtn.setText("Submit");
        UploadAttendance_SubmitBtn.setBorder(null);
        UploadAttendance_SubmitBtn.setBorderPainted(false);
        UploadAttendance_SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UploadAttendance_SubmitBtn.setFocusPainted(false);
        UploadAttendance_SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAttendance_SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UploadAttendance_SubmitBtn);
        UploadAttendance_SubmitBtn.setBounds(80, 550, 100, 38);

        Back_Btn.setBackground(new java.awt.Color(38, 36, 36));
        Back_Btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Go back");
        Back_Btn.setBorder(null);
        Back_Btn.setBorderPainted(false);
        Back_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back_Btn.setFocusPainted(false);
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(1070, 620, 90, 30);

        table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No.", "Student Name", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        table.setRowMargin(5);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 210, 760, 280);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 83));
        jLabel4.setText("Upload Attendance");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 140, 350, 30);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1210, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UploadAttendance_SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAttendance_SubmitBtnActionPerformed
        boolean check=true;
	for( int i = 0; i < rcnt; i++ ) {
            try {
        	File f2 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/CheckedAttendance.txt" );
        	FileWriter fw = new FileWriter( f2, true );
                
        	String rno = sturno[i];
    		String name = stuname[i];
    		String attend;
    		String date = studate[i];
                String attendance = String.valueOf( table.getValueAt( i, 2 ) );
                
                System.out.println(attendance);
    		
                if ( attendance.equals("true") ) {
        		attend = "Present";
        	}
        	else {
        		attend = "Absent";
        	}
                
        	String total = rno + "," + name + "," + attend + "," + date + "\n";
        	fw.write(total);
        	fw.close();
            }
            
            catch(Exception f) {
        	JOptionPane.showMessageDialog( null, f );
            }
        }
        	
        try {
		File f3 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/UploadAttendance.txt") ;
		FileWriter sc = new FileWriter( f3 );
		sc.write( "" );
		sc.close();
	}
        catch(Exception g){
		JOptionPane.showMessageDialog( null, g );
	}
	
        if( check ) {
		JOptionPane.showMessageDialog( null, "Attendance successfully uploaded!" );
                
		Upload_Attendance ad = new Upload_Attendance();
		ad.setVisible( true );
		dispose();
	}        
    }//GEN-LAST:event_UploadAttendance_SubmitBtnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Driver d = new Driver();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance_Roll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance_Roll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance_Roll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance_Roll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance_Roll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton UploadAttendance_SubmitBtn;
    private javax.swing.JLabel background_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
