
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class Driver extends javax.swing.JFrame {

    /**
     * Creates new form Driver
     */
    public Driver() {
        initComponents();
    }
    
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        AdminBtn = new javax.swing.JButton();
        FacultyBtn = new javax.swing.JButton();
        StudentBtn = new javax.swing.JButton();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon("/Users/elizmariemanalo/NetBeansProjects/AMS/images/logo.png")); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(130, 220, 427, 181);

        AdminBtn.setBackground(new java.awt.Color(255, 255, 255));
        AdminBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AdminBtn.setForeground(new java.awt.Color(22, 0, 83));
        AdminBtn.setText("Admin");
        AdminBtn.setBorder(null);
        AdminBtn.setBorderPainted(false);
        AdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdminBtn.setFocusPainted(false);
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AdminBtn);
        AdminBtn.setBounds(130, 470, 113, 38);

        FacultyBtn.setBackground(new java.awt.Color(255, 255, 255));
        FacultyBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FacultyBtn.setForeground(new java.awt.Color(22, 0, 83));
        FacultyBtn.setText("Faculty");
        FacultyBtn.setBorder(null);
        FacultyBtn.setBorderPainted(false);
        FacultyBtn.setFocusPainted(false);
        FacultyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(FacultyBtn);
        FacultyBtn.setBounds(310, 470, 113, 38);

        StudentBtn.setBackground(new java.awt.Color(255, 255, 255));
        StudentBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        StudentBtn.setForeground(new java.awt.Color(22, 0, 83));
        StudentBtn.setText("Student");
        StudentBtn.setBorder(null);
        StudentBtn.setBorderPainted(false);
        StudentBtn.setFocusPainted(false);
        StudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(StudentBtn);
        StudentBtn.setBounds(500, 470, 113, 38);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1200, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        close();
        Admin_Main admin_main = new Admin_Main();
        admin_main.setVisible( true );
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void FacultyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyBtnActionPerformed
        close();
        Faculty_Main faculty_main = new Faculty_Main();
        faculty_main.setVisible( true );
    }//GEN-LAST:event_FacultyBtnActionPerformed

    private void StudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentBtnActionPerformed
//        close();
        Student_Main stu_main = new Student_Main();
        stu_main.setVisible( true );
        dispose();
    }//GEN-LAST:event_StudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JButton FacultyBtn;
    private javax.swing.JButton StudentBtn;
    private javax.swing.JLabel background_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
