/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class Student_board extends javax.swing.JFrame {

    /**
     * Creates new form Student_board
     */
    public Student_board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ViewAttendance_btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 677));

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 0, 83));
        jLabel5.setText("You're signed in as Student");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 210, 490, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 83));
        jLabel4.setText("Welcome!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 170, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-small.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 50, 233, 99);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 0, 83));
        jLabel3.setText("Choose what you want to do");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 420, 280, 30);

        ViewAttendance_btn.setBackground(new java.awt.Color(255, 255, 255));
        ViewAttendance_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ViewAttendance_btn.setForeground(new java.awt.Color(22, 0, 83));
        ViewAttendance_btn.setText("View Attendance");
        ViewAttendance_btn.setBorder(null);
        ViewAttendance_btn.setBorderPainted(false);
        ViewAttendance_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewAttendance_btn.setFocusPainted(false);
        ViewAttendance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAttendance_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewAttendance_btn);
        ViewAttendance_btn.setBounds(130, 490, 190, 38);

        Back_Btn.setBackground(new java.awt.Color(38, 36, 36));
        Back_Btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Logout");
        Back_Btn.setBorder(null);
        Back_Btn.setBorderPainted(false);
        Back_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back_Btn.setFocusPainted(false);
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(1070, 620, 90, 30);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1210, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAttendance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAttendance_btnActionPerformed
        Student_ViewAttendance d = new Student_ViewAttendance();
        d.setVisible(true);
    }//GEN-LAST:event_ViewAttendance_btnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Driver d = new Driver();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton ViewAttendance_btn;
    private javax.swing.JLabel background_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
