
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class Student_Main extends javax.swing.JFrame {

    /**
     * Creates new form Student_Main
     */
    public Student_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Student_Username = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        Student_Password = new javax.swing.JPasswordField();
        StudentLogin_Btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 697));
        setPreferredSize(new java.awt.Dimension(1201, 677));

        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon("/Users/elizmariemanalo/NetBeansProjects/AMS/images/logo.png")); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(130, 220, 427, 181);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 0, 83));
        jLabel3.setText("Sign in as Student");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(670, 160, 180, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 115, 115));
        jLabel4.setText("Username (ID)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(670, 240, 180, 30);

        Student_Username.setBackground(new java.awt.Color(255, 255, 255));
        Student_Username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Student_Username.setForeground(new java.awt.Color(22, 0, 83));
        Student_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Student_Username.setOpaque(false);
        jPanel1.add(Student_Username);
        Student_Username.setBounds(670, 280, 340, 30);

        jlabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(115, 115, 115));
        jlabel.setText("Password");
        jPanel1.add(jlabel);
        jlabel.setBounds(670, 360, 180, 30);

        Student_Password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Student_Password.setForeground(new java.awt.Color(22, 0, 83));
        Student_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Student_Password.setOpaque(false);
        jPanel1.add(Student_Password);
        Student_Password.setBounds(670, 400, 340, 30);

        StudentLogin_Btn.setBackground(new java.awt.Color(255, 255, 255));
        StudentLogin_Btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        StudentLogin_Btn.setForeground(new java.awt.Color(22, 0, 83));
        StudentLogin_Btn.setText("Login");
        StudentLogin_Btn.setBorder(null);
        StudentLogin_Btn.setBorderPainted(false);
        StudentLogin_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StudentLogin_Btn.setFocusPainted(false);
        StudentLogin_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentLogin_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(StudentLogin_Btn);
        StudentLogin_Btn.setBounds(670, 500, 90, 38);

        Back_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Back_Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(22, 0, 83));
        Back_Btn.setText("Go back");
        Back_Btn.setBorder(null);
        Back_Btn.setBorderPainted(false);
        Back_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back_Btn.setFocusPainted(false);
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(1070, 620, 90, 30);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1200, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentLogin_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentLogin_BtnActionPerformed

        boolean check = true;
	
        try {
		File f1 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/StudentList.txt" );
		Scanner rd = new Scanner(f1);
		rd.useDelimiter( "\\n|," );
                
		while( rd.hasNext() ) {
                        rd.next();
			String s1 = rd.next();
			String s2 = rd.next();
			rd.nextLine();
			
                        if( Student_Username.getText().equals(s1) && Student_Password.getText().equals(s2)) {
				
                                try {
					File f2 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/Student_ViewAttendance.txt" );
					FileWriter fw = new FileWriter(f2);
					String sturno = Student_Username.getText();
					fw.write( sturno );
					fw.close();
				}
				
                                catch( Exception f ) {
					JOptionPane.showMessageDialog( null, f );
				}

				JOptionPane.showMessageDialog( null, "You have successfully logged in!" );
				
                                Student_board stu_board = new Student_board();
                                stu_board.setVisible( true );
                                dispose();
				
                                check=false;
			}
		}
		
                if ( check ){
			JOptionPane.showMessageDialog( null, "Wrong Username or Password!" );
		}
	}
	
        catch( Exception f ) {
		JOptionPane.showMessageDialog( null, f );
	}
    }//GEN-LAST:event_StudentLogin_BtnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Driver d = new Driver();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton StudentLogin_Btn;
    private javax.swing.JPasswordField Student_Password;
    private javax.swing.JTextField Student_Username;
    private javax.swing.JLabel background_image;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
