
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class Upload_Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Upload_Attendance
     */
    public Upload_Attendance() {
        initComponents();
        
        try {
            File f3 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/UploadAttendance.txt" );
            FileWriter sc = new FileWriter( f3 );
            sc.write( "" ); 
            sc.close();
        }
        catch( Exception g ){
            JOptionPane.showMessageDialog( null, g );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Dept_Dropdown = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Semester_Dropdown = new javax.swing.JComboBox<>();
        Section = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UploadAttendance_SubmitBtn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1202, 677));

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-small.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 50, 233, 99);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 83));
        jLabel4.setText("Upload Attendance");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 170, 350, 30);

        Dept_Dropdown.setBackground(new java.awt.Color(255, 255, 255));
        Dept_Dropdown.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Dept_Dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIT", "LIB", "ECE", "CCE" }));
        Dept_Dropdown.setOpaque(false);
        Dept_Dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dept_DropdownActionPerformed(evt);
            }
        });
        jPanel1.add(Dept_Dropdown);
        Dept_Dropdown.setBounds(130, 300, 260, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(115, 115, 115));
        jLabel9.setText("Department:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 260, 180, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(115, 115, 115));
        jLabel10.setText("Semester:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 260, 180, 30);

        Semester_Dropdown.setBackground(new java.awt.Color(255, 255, 255));
        Semester_Dropdown.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Semester_Dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        Semester_Dropdown.setOpaque(false);
        jPanel1.add(Semester_Dropdown);
        Semester_Dropdown.setBounds(450, 300, 260, 30);

        Section.setBackground(new java.awt.Color(255, 255, 255));
        Section.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Section.setForeground(new java.awt.Color(22, 0, 83));
        Section.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Section.setOpaque(false);
        jPanel1.add(Section);
        Section.setBounds(760, 300, 250, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(115, 115, 115));
        jLabel7.setText("Section:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(760, 260, 180, 30);

        Date.setBackground(new java.awt.Color(255, 255, 255));
        Date.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(22, 0, 83));
        Date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Date.setOpaque(false);
        jPanel1.add(Date);
        Date.setBounds(130, 420, 250, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(115, 115, 115));
        jLabel8.setText("Date:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 380, 180, 30);

        UploadAttendance_SubmitBtn.setBackground(new java.awt.Color(255, 255, 255));
        UploadAttendance_SubmitBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UploadAttendance_SubmitBtn.setForeground(new java.awt.Color(22, 0, 83));
        UploadAttendance_SubmitBtn.setText("Submit");
        UploadAttendance_SubmitBtn.setBorder(null);
        UploadAttendance_SubmitBtn.setBorderPainted(false);
        UploadAttendance_SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UploadAttendance_SubmitBtn.setFocusPainted(false);
        UploadAttendance_SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAttendance_SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UploadAttendance_SubmitBtn);
        UploadAttendance_SubmitBtn.setBounds(130, 510, 100, 38);

        Back_Btn.setBackground(new java.awt.Color(38, 36, 36));
        Back_Btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Go back");
        Back_Btn.setBorder(null);
        Back_Btn.setBorderPainted(false);
        Back_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back_Btn.setFocusPainted(false);
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(1070, 620, 90, 30);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 1210, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UploadAttendance_SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAttendance_SubmitBtnActionPerformed
        try {
		File f1 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/StudentList.txt" );
                
		Scanner rd = new Scanner( f1 );
		Scanner sc = new Scanner( f1 );
                
		rd.useDelimiter( "\\n|," );
		sc.useDelimiter( "\\n|," );
		
                while( rd.hasNextLine() ) {
			String x1, x2, x3;
                        
			rd.next();
			rd.next();
			rd.next();
			rd.next();
                        
			x1 = rd.next();
			x3 = rd.next();
			x2 = rd.next();
                        
			rd.nextLine();
                        
			String stuname = sc.next();
			String sturno = sc.next();
			String studate = Date.getText();
			sc.nextLine();
			
                        if( x1.equals( (String)Dept_Dropdown.getSelectedItem() ) && x2.equals( (String)Semester_Dropdown.getSelectedItem() ) && x3.equals( Section.getText() )) {
				File f2 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/UploadAttendance.txt" );
				FileWriter fw = new FileWriter( f2, true );
                                
				String total = sturno + "," + stuname + "," + studate + "\n";
                                
				fw.write( total );
				fw.close();
			}							
		}
	}
	
        catch( Exception f ) {
						
	}
	
        Attendance_Roll ar = new Attendance_Roll();
	ar.setVisible( true );
	dispose();
    }//GEN-LAST:event_UploadAttendance_SubmitBtnActionPerformed

    private void Dept_DropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dept_DropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dept_DropdownActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Driver d = new Driver();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upload_Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JTextField Date;
    private javax.swing.JComboBox<String> Dept_Dropdown;
    private javax.swing.JTextField Section;
    private javax.swing.JComboBox<String> Semester_Dropdown;
    private javax.swing.JButton UploadAttendance_SubmitBtn;
    private javax.swing.JLabel background_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
