
import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elizmariemanalo
 */
public class View_Attendance extends javax.swing.JFrame {

    /**
     * Creates new form View_Attendance
     */
    public View_Attendance() {
        initComponents();
    }
    
    String user;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rollNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UploadAttendance_SubmitBtn = new javax.swing.JButton();
        AttendanceResult = new javax.swing.JLabel();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        rollNo.setBackground(new java.awt.Color(255, 255, 255));
        rollNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rollNo.setForeground(new java.awt.Color(22, 0, 83));
        rollNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        rollNo.setOpaque(false);
        jPanel1.add(rollNo);
        rollNo.setBounds(190, 110, 40, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 0, 83));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Attendance");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 30, 350, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 115, 115));
        jLabel5.setText("Please enter Roll No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 140, 20);

        UploadAttendance_SubmitBtn.setBackground(new java.awt.Color(255, 255, 255));
        UploadAttendance_SubmitBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UploadAttendance_SubmitBtn.setForeground(new java.awt.Color(22, 0, 83));
        UploadAttendance_SubmitBtn.setText("View");
        UploadAttendance_SubmitBtn.setBorder(null);
        UploadAttendance_SubmitBtn.setBorderPainted(false);
        UploadAttendance_SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UploadAttendance_SubmitBtn.setFocusPainted(false);
        UploadAttendance_SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAttendance_SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UploadAttendance_SubmitBtn);
        UploadAttendance_SubmitBtn.setBounds(360, 220, 70, 38);

        AttendanceResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AttendanceResult.setForeground(new java.awt.Color(22, 0, 83));
        AttendanceResult.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(AttendanceResult);
        AttendanceResult.setBounds(40, 160, 280, 100);

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        background_image.setText("jLabel2");
        jPanel1.add(background_image);
        background_image.setBounds(0, 0, 460, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UploadAttendance_SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAttendance_SubmitBtnActionPerformed
        Float pcnt = new Float(0);
	Float totcnt = new Float(0);
	Float att = new Float(0);
	
        try {
                user = rollNo.getText();
									
		File f2 = new File( "/Users/elizmariemanalo/NetBeansProjects/AMS/Records/CheckedAttendance.txt" );
		Scanner sc = new Scanner( f2 );
		sc.useDelimiter( "\\n|," );
		
                while( sc.hasNextLine() ) {
			if( user.equals( sc.next() )) {
				sc.next();
				
                                if( sc.next().equals( "Present" )) {
                                    pcnt++;
                                    totcnt++;
				}
                                else
                                        totcnt++;
                                        sc.nextLine();
                                }
                        
			else {
				sc.nextLine();
			}
		}
		
                sc.close();
						
		att = ( ( pcnt/totcnt ) * 100 );
	}
	
        catch( Exception f ) {
		JOptionPane.showMessageDialog( null, f );
	}
	
        String stratt = att.toString();
					
	AttendanceResult.setText( "Attendance Percentage: " + stratt );
    }//GEN-LAST:event_UploadAttendance_SubmitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttendanceResult;
    private javax.swing.JButton UploadAttendance_SubmitBtn;
    private javax.swing.JLabel background_image;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rollNo;
    // End of variables declaration//GEN-END:variables
}
